"""monthly_menu

Revision ID: 53ca80a6c153
Revises: 
Create Date: 2026-05-26 14:25:04.066944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ca80a6c153'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('menus', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_menus_date'), table_name='menus')
    op.create_index(op.f('ix_menus_month'), 'menus', ['month'], unique=False)
    op.create_index(op.f('ix_menus_year'), 'menus', ['year'], unique=False)
    op.drop_column('menus', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_menus_year'), table_name='menus')
    op.drop_index(op.f('ix_menus_month'), table_name='menus')
    op.create_index(op.f('ix_menus_date'), 'menus', ['date'], unique=True)
    op.drop_column('menus', 'year')
    op.drop_column('menus', 'month')
    # ### end Alembic commands ###
