"""add is_published to monthly config

Revision ID: 6a4e62b240b6
Revises: ec42baadcf19
Create Date: 2026-06-18 12:42:18.105430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4e62b240b6'
down_revision: Union[str, Sequence[str], None] = 'ec42baadcf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_config_id'), table_name='monthly_config')
    op.drop_index(op.f('ix_monthly_config_month'), table_name='monthly_config')
    op.drop_index(op.f('ix_monthly_config_year'), table_name='monthly_config')
    op.drop_table('monthly_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('per_day_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('monthly_config_pkey'))
    )
    op.create_index(op.f('ix_monthly_config_year'), 'monthly_config', ['year'], unique=False)
    op.create_index(op.f('ix_monthly_config_month'), 'monthly_config', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_config_id'), 'monthly_config', ['id'], unique=False)
    # ### end Alembic commands ###
