"""add_admission_year_and_year_of_study

Revision ID: ba86f85cda8e
Revises: f96350abb6a3
Create Date: 2026-06-18 11:39:44.481425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba86f85cda8e'
down_revision: Union[str, Sequence[str], None] = 'f96350abb6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admission_year', sa.String(), nullable=True))
    op.add_column('users', sa.Column('year_of_study', sa.Integer(), nullable=True))
    op.add_column('whitelist', sa.Column('admission_year', sa.String(), nullable=True))
    op.add_column('whitelist', sa.Column('year_of_study', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelist', 'year_of_study')
    op.drop_column('whitelist', 'admission_year')
    op.drop_column('users', 'year_of_study')
    op.drop_column('users', 'admission_year')
    # ### end Alembic commands ###
