"""Add holidays table

Revision ID: f96350abb6a3
Revises: 30aa225bc92b
Create Date: 2026-06-12 11:40:17.484864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96350abb6a3'
down_revision: Union[str, Sequence[str], None] = '30aa225bc92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'description')
    # ### end Alembic commands ###
